In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv(r'C:\Users\yamini\Downloads\dataset.csv')

In [3]:
dataset

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                     -1              -1                           -1  ...   
1                      0               1                           -1  ...   
2                     -1              -1                           -1  ...   
3                     -1              -1                            1  ...   
4                      1               1                           -1  ...   
...                  ...             ...                          ...  ...   
11050                  1               1                           -1  ...   
11051                  1              -1                           -1  ...   
11052                  1              -1                           -1  ...   
11053                 -1              -1                            1  ...   
11054                 -1              -1                            1  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0                1       1             -1         -1           -1         -1   
1                1       1             -1         -1            0         -1   
2                1       1              1         -1            1         -1   
3                1       1             -1         -1            1         -1   
4               -1       1             -1         -1            0         -1   
...            ...     ...            ...        ...          ...        ...   
11050           -1      -1              1          1           -1         -1   
11051           -1       1              1          1            1          1   
11052            1       1              1          1            1         -1   
11053           -1       1              1          1            1         -1   
11054            1       1             -1          1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
0                 1                       1                  -1      -1  
1                 1                       1                   1      -1  
2                 1                       0                  -1      -1  
3                 1                      -1    

In [4]:
dataset.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

In [6]:
dataset.drop(['index'],axis=1,inplace=True)

In [7]:
dataset

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                              -1              1                   1   
1                               1              1                   1   
2                               1              0                   1   
3                               1              0                   1   
4                               1              0                  -1   
...                           ...            ...                 ...   
11050                           1             -1                   1   
11051                          -1              1                   1   
11052                           1             -1                   1   
11053                          -1             -1                   1   
11054                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  \
0                     -1              -1                           -1   
1                      0               1                           -1   
2                     -1              -1                           -1   
3                     -1              -1                            1   
4                      1               1                           -1   
...                  ...             ...                          ...   
11050                  1               1                           -1   
11051                  1              -1                           -1   
11052                  1              -1                           -1   
11053                 -1              -1                            1   
11054                 -1              -1                            1   

       Favicon  ...  popUpWidnow  Iframe  age_of_domain  DNSRecord  \
0            1  ...            1       1             -1         -1   
1            1  ...            1       1             -1         -1   
2            1  ...            1       1              1         -1   
3            1  ...            1       1             -1         -1   
4            1  ...           -1       1             -1         -1   
...        ...  ...          ...     ...            ...        ...   
11050       -1  ...           -1      -1              1          1   
11051       -1  ...           -1       1              1          1   
11052        1  ...            1       1              1          1   
11053       -1  ...           -1       1              1          1   
11054        1  ...            1       1             -1          1   

       web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0               -1         -1             1                       1   
1                0         -1             1                       1   
2                1         -1             1                       0   
3                1         -1             1                      -1   
4                0         -1             1                       1   
...            ...        ...           ...                     ...   
11050           -1         -1             1                       1   
11051            1          1          

In [8]:
x=dataset.iloc[:,0:30].values
y=dataset.iloc[:,30].values

In [9]:
x

array([[-1,  1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  0,  1, ...,  1,  0, -1],
       ...,
       [ 1, -1,  1, ...,  1,  0,  1],
       [-1, -1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ..., -1,  1, -1]], dtype=int64)

In [10]:
y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [11]:
x.shape

(11055, 30)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [14]:
x_test.shape

(2211, 30)

In [15]:
x_train.shape

(8844, 30)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
#Logistic Regression classifier

from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_pred = logistic.predict(x_test)

In [19]:
y_pred

array([-1, -1,  1, ..., -1, -1,  1], dtype=int64)

In [20]:
y_test

array([-1, -1, -1, ...,  1,  1,  1], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score
logacc = accuracy_score(y_test,y_pred)

In [22]:
logacc

0.9167797376752601

In [26]:
acc= 100.0 * logacc

print ("The accuracy of our Logistic Regression on testing data is: " + str(acc))

The accuracy of our Logistic Regression on testing data is: 91.67797376752601


In [27]:
#Decision Tree classifier

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [28]:
decisiontree = classifier.predict(x_test)

In [29]:
decisiontree

array([-1, -1,  1, ..., -1,  1,  1], dtype=int64)

In [30]:
y_test

array([-1, -1, -1, ...,  1,  1,  1], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test,decisiontree)

In [32]:
cm2

array([[ 963,   51],
       [  31, 1166]], dtype=int64)

In [34]:
from sklearn.metrics import accuracy_score
desacc = accuracy_score(y_test,decisiontree)
     

In [35]:
desacc

0.9629127091813658

In [46]:
acc1= 100.0 * desacc

print ("The accuracy of our Decision Tree on testing data is: " + str(acc1))

The accuracy of our Decision Tree on testing data is: 96.29127091813659


In [38]:
#Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
rand = RandomForestClassifier(n_estimators = 20 , random_state = 0)
rand.fit(x_train,y_train) 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [39]:
randonforest = rand.predict(x_test)

In [40]:
randonforest

array([-1, -1,  1, ...,  1,  1,  1], dtype=int64)

In [41]:
y_test

array([-1, -1, -1, ...,  1,  1,  1], dtype=int64)

In [42]:
cm3 = confusion_matrix(y_test,randonforest)

In [43]:
cm3

array([[ 963,   51],
       [  14, 1183]], dtype=int64)

In [44]:
randacc = accuracy_score(y_test,randonforest)

In [45]:
randacc

0.9706015377657169

In [47]:
acc2= 100.0 * randacc

print ("The accuracy of our Random Forest on testing data is: " + str(acc2))

The accuracy of our Random Forest on testing data is: 97.0601537765717


In [48]:
#Knn Classifier

from sklearn.neighbors import KNeighborsClassifier
knn =  KNeighborsClassifier(n_neighbors = 5 , metric = 'minkowski')
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [49]:
knnpred = knn.predict(x_test)

In [50]:
knnacc = accuracy_score(y_test,knnpred)

In [51]:
knnacc

0.9380370872908186

In [53]:
acc3= 100.0 * knnacc

print ("The accuracy of our Knn reg on testing data is: " + str(acc3))

The accuracy of our Knn reg on testing data is: 93.80370872908186


In [55]:
#Naive Bayes Classifier

from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [57]:
napred = naive.predict(x_test)

In [58]:
naacc = accuracy_score(y_test,napred)

In [59]:
naacc

0.6101311623699683

In [60]:
acc4= 100.0 * naacc

print ("The accuracy of our naive bayes on testing data is: " + str(acc4))

The accuracy of our naive bayes on testing data is: 61.01311623699684


In [61]:
#SVM Classifier

from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(x_train, y_train)



SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [64]:
#Predict the response for test dataset
svmpred = clf.predict(x_test)

In [65]:
svmacc = accuracy_score(y_test,svmpred)

In [66]:
svmacc

0.9181365897783809

In [67]:
acc5= 100.0 * svmacc

print ("The accuracy of our Svm classifier on testing data is: " + str(acc5))

The accuracy of our Svm classifier on testing data is: 91.81365897783809
